name: Domain Deƒüi≈üiklik Kontrol√º

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: 11 */9 * * *

jobs:
  DomainKontrol:
    runs-on: ubuntu-latest

    env:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Depo Kontrol√º
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # T√ºm ge√ßmi≈üi √ßek

      - name: Python 3.11.8 Y√ºkle
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Python S√ºr√ºm√ºm√º G√∂ster
        run: python -c "import sys; print(sys.version)"

      - name: Gereksinimleri Y√ºkle
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik cloudscraper

      - name: Betiƒüi √áalƒ±≈ütƒ±r
        run: python KONTROL.py

      - name: Debug - Git Durumu
        run: |
          git status
          git log --oneline -5
          git diff

      - name: Deƒüi≈üiklik Kontrol√º
        id: degisiklik_kontrol
        run: |
          if git diff --quiet HEAD; then
            echo "degisiklik=false" >> $GITHUB_ENV
          else
            echo "degisiklik=true" >> $GITHUB_ENV
          fi

      - name: Pull Request Olu≈ütur
        if: env.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "196586221+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit --author="sarapcanagii <sarapcanagii@users.noreply.github.com>" \
            -m "‚ôªÔ∏è Domain Deƒüi≈üikliƒüi" \
            -m "üîÑ Otomatik domain g√ºncellemeleri yapƒ±ldƒ±."

          BRANCH="domain-degisikligi"
          git checkout -B $BRANCH
          git push origin $BRANCH --force

          curl -X POST -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls \
            -d @- <<EOF
          {
            "title": "‚ôªÔ∏è Domain Deƒüi≈üikliƒüi",
            "head": "$BRANCH",
            "base": "master",
            "body": "üîÑ Otomatik tespit edilen domain deƒüi≈üiklikleri uygulandƒ±.\n\nüìÇ ƒ∞lgili dosyalar g√ºncellendi. L√ºtfen deƒüi≈üiklikleri g√∂zden ge√ßirin ve onaylayƒ±n."
          }
          EOF